### ISSUE TITLE
Editor Config?

### ISSUE THREAD

**Issue by bloggervista** [khalti/khalti-docs-official-repo#2]
Was trying to PR API portion but I didn't understand the convention used for writing docs. Can we create custom editor config and create contribution guide. And it will be useful to use Jekyll as we don't need to duplicate many codes.

**Comment by ludbek** [comment]
Thanks for reporting :)

https://github.com/khalti/khalti-docs-official-repo/commit/cb12368721c2aa2ea2a9013a090ede26c34f40f6

**Comment by ludbek** [comment]
Contribution info will be added soon
